services:
  mysql:
    container_name: mysql
    image: mysql:8.2
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: db_sample_shop
    volumes:
      - .docker/mysql/data:/var/lib/mysql