server:
  servlet:
    context-path: /api/v1
  port: ${APP_PORT}

spring:
  application:
    name: sample-shop
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: 'health,prometheus'
    endpoint:
      health:
        enabled: true
        show-details: always
      prometheus:
        enabled: true