global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "products-api"
    metrics_path: /api/v1/actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]
        labels:
          application: "products-api"